-- Every message in a recent date range.
-- Generated by scripts/build-backfill-queries.cjs.
-- Run in the BigQuery console (the free sandbox works, no card needed), save
-- the results as CSV, and import them with
--   npm run backfill:import -- backfill/<file>.csv
--
-- Cost: BigQuery bills by data scanned, and this reads the calldata of every
-- transaction in the date range. Check the estimate in the top right of the
-- editor before running. The first 1 TB a month is free; shorten the range if
-- the estimate is higher than that.
--
-- The output has the decoded text in a "body" column and is pre-filtered with
-- the same spam rules as the app, so the file stays small.
DECLARE start_ts TIMESTAMP DEFAULT TIMESTAMP('2025-10-01');
DECLARE end_ts   TIMESTAMP DEFAULT TIMESTAMP('2026-10-09');

WITH tx AS (
  SELECT
    `hash`, block_number, block_timestamp, transaction_index, from_address, to_address,
    CAST(value AS STRING) AS value,
    REGEXP_REPLACE(SAFE_CONVERT_BYTES_TO_STRING(FROM_HEX(SUBSTR(input, 3))), r'^\x00+|\x00+$', '') AS body
  FROM `bigquery-public-data.crypto_ethereum.transactions`
  WHERE block_timestamp >= start_ts AND block_timestamp < end_ts
    AND to_address IS NOT NULL
    AND input != '0x'
    AND LENGTH(input) BETWEEN 6 AND 40002
),
msgs AS (
  SELECT * FROM tx
  WHERE body IS NOT NULL                                   -- valid UTF-8
    AND NOT REGEXP_CONTAINS(body, r'\x00')                -- no NUL bytes inside, so not ABI-encoded
    AND REGEXP_CONTAINS(body, r'\pL.*\pL')               -- at least two letters
    AND NOT STARTS_WITH(body, 'data:')                     -- inscriptions
    AND NOT REGEXP_CONTAINS(body, r'^\s*\{\s*"p"\s*:')
    AND NOT REGEXP_CONTAINS(body, r'^[A-Z0-9]+([_:.-][A-Z0-9]+)+$')  -- exchange and bot tags
    AND NOT REGEXP_CONTAINS(body, r'^[A-Za-z0-9+/=_-]{48,}$')        -- encoded payloads
),
-- Same spam rules as the app, applied here so the export stays small.
blasts AS (
  SELECT from_address, body FROM msgs GROUP BY 1, 2 HAVING COUNT(DISTINCT to_address) >= 10
),
farms AS (
  SELECT body FROM msgs WHERE LENGTH(body) >= 20 GROUP BY 1 HAVING COUNT(DISTINCT from_address) >= 25
)
SELECT m.`hash`, m.block_number, m.block_timestamp, m.transaction_index,
       m.from_address, m.to_address, m.value, m.body
FROM msgs m
LEFT JOIN blasts b ON b.from_address = m.from_address AND b.body = m.body
LEFT JOIN farms f ON f.body = m.body
WHERE b.from_address IS NULL AND f.body IS NULL
ORDER BY m.block_number;
