// Writes db/setup.sql: the schema plus every label, as one file you can paste
// into a SQL editor (Supabase, Neon) when you can't run npm scripts against
// the database. Usage: npx tsx scripts/build-setup-sql.ts
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { SCHEMA } from "../lib/schema";
import { allIncidents, allLabels } from "../lib/setup";

const q = (s: string | undefined | null) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);
const labels = allLabels();
const values = labels
  .map((l) => `  (${q(l.address)}, ${q(l.name)}, ${q(l.kind)}, ${q(l.source)}, ${q(l.incident)})`)
  .join(",\n");
const incidents = allIncidents()
  .map((i) => `  (${q(i.slug)}, ${q(i.name)})`)
  .join(",\n");

const sql = `-- Generated by scripts/build-setup-sql.ts. Safe to run more than once.
${SCHEMA}
insert into incidents (slug, name) values
${incidents}
on conflict (slug) do update set name = excluded.name;

insert into labels (address, name, kind, source, incident) values
${values}
on conflict (address) do update
  set name = excluded.name, kind = excluded.kind, source = excluded.source, incident = excluded.incident;
`;
mkdirSync(join(process.cwd(), "db"), { recursive: true });
writeFileSync(join(process.cwd(), "db/setup.sql"), sql);
console.log(`Wrote db/setup.sql with ${labels.length} labels.`);
