// Writes db/setup.sql: the schema plus every label, as one file you can paste
// into a SQL editor (Supabase, Neon) when you can't run npm scripts against
// the database. Usage: npx tsx scripts/build-setup-sql.ts
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

type Label = { address: string; name: string; kind: string; source?: string };
const root = process.cwd();
const load = (f: string): Label[] =>
  existsSync(join(root, "data", f)) ? JSON.parse(readFileSync(join(root, "data", f), "utf8")) : [];

const merged = new Map<string, Label>();
for (const l of [...load("labels.json"), ...load("labels-custom.json")]) merged.set(l.address.toLowerCase(), l);

const q = (s: string | undefined | null) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);
const values = [...merged.values()]
  .map((l) => `  (${q(l.address.toLowerCase())}, ${q(l.name)}, ${q(l.kind)}, ${q(l.source)})`)
  .join(",\n");

const sql = `-- Generated by scripts/build-setup-sql.ts. Safe to run more than once.
${readFileSync(join(root, "db/schema.sql"), "utf8")}
insert into labels (address, name, kind, source) values
${values}
on conflict (address) do update
  set name = excluded.name, kind = excluded.kind, source = excluded.source;
`;
writeFileSync(join(root, "db/setup.sql"), sql);
console.log(`Wrote db/setup.sql with ${merged.size} labels.`);
